import axios from "axios";
import Head from "next/head";
import TabelProduct from "../components/TabelProduct";

export default function Home({ products, value }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TabelProduct products={products} value={value} />
      </main>

      <footer></footer>
    </div>
  );
}

export const getServerSideProps = async () => {
  const value = "";
  const res = await axios.get(`https://dummyjson.com/products/${value}`);

  return {
    props: { products: res.data, value: value },
  };
};
