import Head from "next/head";
import TabelProduct from "../components/TabelProduct";



export default function Home({products}) {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       <TabelProduct products={products}/>
      </main>

      <footer></footer>
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch('https://dummyjson.com/products');
  const data = await res.json();

  return {
    props: {products: data}
  }
} 
